import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body suppressHydrationWarning className={`${inter.className} bg-slate-900  max-w-screen-md mx-auto px-3  md:px-6`}>
            {children}
        </body>
    </html>
  )
}
